# Generated by Django 4.1.7 on 2023-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_img',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
